version: "3.5"
services:
  app:
    image: lenchv/bsa-php:0.0.2
    environment:
      XDEBUG_CONFIG: "remote_host=172.17.0.1 remote_port=9001 remote_log=/app/xdebug.log"
    volumes:
      - ./:/app
    working_dir: /app
  composer:
    image: composer:latest
    volumes:
        - ./:/app
        - ./.composer:/composer
  db:
    image: mariadb:latest
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
